### ISSUE TITLE
Add handling for cow files with custom colors

### ISSUE THREAD

**Issue by 2br-2b** [James-Ansley/cowsay#2]
Hello!

First off, thank you for making this library!

Right now, if you use a custom colored cow file (like some of the examples [here](https://github.com/paulkaefer/cowsay-files/tree/main/cows), the cow will not properly be converted to text.

String output:
![image](https://github.com/James-Ansley/cowsay/assets/43968991/8293bdb7-d279-4cf4-bba2-c563b26abedc)

cowfile: [batman.cow](https://github.com/paulkaefer/cowsay-files/blob/main/cows/batman.cow)

Theoretically, string substitution could be used to create variables and substitute throughout the file... but at that point, you're almost creating a bash shell in python

My proposed solution is to do a simple check in `read_dot_cow()`. If the line starts with a `$` and has an `=` sign, it should remove all color formatting from the string (or have an option to leave it in) and add it to another dictionary, similar to `ESCAPES`, and replace all these variables at the end.

**Comment by 2br-2b** [comment]
Another few options:

Turn the cowfiles into silhouettes; there's no way you can get this level of detail in a python string:
![image](https://github.com/James-Ansley/cowsay/assets/43968991/2bdf3c14-0653-468c-a548-c25fd5e5481b)


Remove all the $s:
![image](https://github.com/James-Ansley/cowsay/assets/43968991/656299e6-b596-4582-b8ba-f43a51d9f746)

**Comment by 2br-2b** [comment]
On further testing, I don't like many of these ideas. Maybe a silhouette will be the best option, or just ignoring it

**Comment by James-Ansley** [comment]
Hi, thanks for pointing this out. Unfortunately, `.cow` files are usually nothing more than Perl files or modules. In order to properly handle **all** cow files, the Perl code would need to actually be run (with Perl) to generate the cow correctly. This means there will be limitations in treating `.cow` files as Python strings.

In saying that, if you _really_ want to fill in the colours, and the `.cow` files you want to process are all formatted in the same way at the `batman.cow` file you linked to (e.g. a bunch of variable declarations for the ansi escape codes which are used in the cow heredoc), then the following code could be used to "fill in" the variables:

```python
import re

from cowsay import read_dot_cow, cowsay

ANSI_PATTERN = re.compile(
    r'(?:^|\n)(\$.+) = "(.+)";'
)

with open("batman.cow", "r") as f:
    replacements = {
        k: v.replace("\\e", "\x1b")
        for k, v in ANSI_PATTERN.findall(f.read())
    }
    f.seek(0)
    cow = read_dot_cow(f, replacements)

print(cowsay("hello", cowfile=cow))
```

**Comment by James-Ansley** [comment]
Just following up on this. I just released a new version of python-cowsay that adds a CLI and also handles the colourful cow files you mentioned. These files should now be rendered with colours by default.
